# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Matematiikkakilpailut
tagline: Suomen matematiikan olympiavalmennus
author :
  name : Suomen matemaattisen yhdistyksen valmennusjaos
  github : matematiikkakilpailut

production_url : http://matematiikkakilpailut.fi
url: http://matematiikkakilpailut.fi
  
plugins:
  - jekyll-sitemap
